# Form implementation generated from reading ui file 'vote_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.totalLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.totalLabel.setGeometry(QtCore.QRect(610, 380, 47, 13))
        self.totalLabel.setObjectName("totalLabel")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 171, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 47, 116))
        self.label_2.setObjectName("label_2")
        self.idLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.idLine.setGeometry(QtCore.QRect(160, 130, 181, 21))
        self.idLine.setObjectName("idLine")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 230, 221, 31))
        self.label_3.setObjectName("label_3")
        self.janeRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.janeRadio.setGeometry(QtCore.QRect(170, 300, 171, 21))
        self.janeRadio.setObjectName("janeRadio")
        self.johnRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.johnRadio.setGeometry(QtCore.QRect(170, 350, 82, 17))
        self.johnRadio.setObjectName("johnRadio")
        self.submitBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitBtn.setGeometry(QtCore.QRect(120, 430, 191, 23))
        self.submitBtn.setObjectName("submitBtn")
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(130, 510, 201, 20))
        self.statusLabel.setObjectName("statusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.totalLabel.setText(_translate("MainWindow", "Total: 0 "))
        self.label.setText(_translate("MainWindow", "VOTING  APPLICATION "))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "CANDIDATES"))
        self.janeRadio.setText(_translate("MainWindow", "Jane "))
        self.johnRadio.setText(_translate("MainWindow", "John"))
        self.submitBtn.setText(_translate("MainWindow", "SUBMIT VOTE "))
        self.statusLabel.setText(_translate("MainWindow", "TextLabel"))
